server:
  # 端口号
  port: 8083

# 开启 debug 模式
#debug: true

#spring:
#  mvc:
#    #  静态资源访问前置
#    static-path-pattern: /res/**
#  web:
#    resources:
#      # 静态资源访问路径
#      static-locations: classpath:/myres

# 启用 HiddenHttpMethodFilter 过滤器，以支持表单发送 PUT、DELETE 等非 GET、POST 请求
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      # 启用基于请求参数的内容协商策略
      favor-parameter: true